apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: task-1
spec:
  inputs:
    resources:
      - name: gitrepo
        type: git
  outputs: 
    resources: 
      - name: gitrepo
        type: git
  steps:
    - name: hello
      image: ubuntu
      command: ["bash", "-ce"]
      args:
      - |
        echo "Hello from task-1"
        cat /workspace/gitrepo/readme.md